### ISSUE TITLE
installation instructions are a bit sparse

### ISSUE THREAD

**Issue by joyously** [idursun/jjui#1]
Do you have to install Go? 
Do you need jjui on the PATH?

**Comment by idursun** [comment]
Hi, yes you would need `go` to be present on your machine.

`go install` should compile and put the final binary in the `GOBIN` (which is normally on the PATH) directory.

I will update the installation instructions with any missing steps once I try these on a fresh machine.

**Comment by idursun** [comment]
I have updated the README.

There are two methods to install `jjui` now. You can build it from the source if you want the latest (requires go tooling). 

Also, @Adda0 kindly created a nix package which can be installed using the nix tooling.

In favour of the two, I am going to close this issue. Let me know if you have any other concerns.

**Comment by joyously** [comment]
Thanks for the effort.
It's a hassle to add either of these to my machine just to try this UI.

**Comment by Adda0** [comment]
@joyously Hey. If you really just want to try it out, one can use the following Nix tooling commands to install Nix, install the [jjui](https://search.nixos.org/packages?channel=unstable&show=jjui&from=0&size=50&sort=relevance&type=packages&query=jjui) package from [nixpkgs](https://github.com/NixOS/nixpkgs/), and uninstall everything once you are done. The beauty of this is that once uninstalled, there will not be any leftover files from either `jjui`, or Nix tooling.  

```sh
# Install Nix.
# WARNING: Piping a script from the internet into a shell. Investigate on your own, if you deem that necessary.
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

# Install `jjui` from `nixpkgs`.
nix profile install nixpkgs#jjui

# Try it out...
jjui

# Remove everything.
/nix/nix-installer uninstall
```

That being said, if you want to go this route, I would advise waiting a few days until the nixpkgs jjui package gets updated to the 0.1 version released today.

**Comment by idursun** [comment]
@joyously Releases [have compiled binaries attached](https://github.com/idursun/jjui/releases/tag/v0.1). You can download one that is compatible with your OS and architecture from there.

**Comment by joyously** [comment]
Oh? Is this new? 
Thank you!

**Comment by Adda0** [comment]
I have not even noticed the pre-compiled binaries. That is even better :+1: And yes, the pre-compiled binaries are new in 0.1, since previously there was no release version to publish the pre-compiled binaries for.
