### ISSUE TITLE
Panic when loading the tree graph of a large repository

### ISSUE THREAD

**Issue by Adda0** [idursun/jjui#4]
Hey. When I tried updating `jjui` in [nixpkgs](https://github.com/NixOS/nixpkgs/) to the commit c868feeef3945639b6816d7cb14e4eecb59bd163 from commit 525c8042a51710cdaefa91176af68a22ad0045bd, `jjui` panics on loading the tree graph of [nixpkgs](https://github.com/NixOS/nixpkgs/) repository, i.e., a large repository with a lot of commits, branches, tags, etc. when running `jjui` in the repository. Works without a problem on smaller repositories.

<details><summary>Panic log</summary>
<p>

```
Caught panic:

runtime error: slice bounds out of range [35:8]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc00015c3c0)
        github.com/charmbracelet/bubbletea@v1.2.4/tea.go:705 +0x8b
panic({0x596a00?, 0xc000258498?})
        runtime/panic.go:785 +0x132
jjui/internal/ui/revisions.SegmentedRenderer.Render({{{0x7563a0, 0x401, {0x0, 0x0}, 0x1, {0x622598, 0xc000126320}, {0x0, 0x0}, 0x0, ...}, ...}, ...}, ...)
        jjui/internal/ui/revisions/renderer.go:42 +0x2390
jjui/internal/jj.RenderRow({_, _}, {0x0, 0x0, 0x2, {{0xc000549069, 0x23}, {0xc00054908d, 0x8}, {0xc00056b040, ...}, ...}, ...}, ...)
        jjui/internal/jj/row.go:27 +0xad
jjui/internal/ui/revisions.Model.View({0xc00023e030, {0xc00059a000, 0xce, 0x111}, 0x1, {0x0, 0x0}, 0x0, 0xc000124560, 0xffffffffffffffff, ...})
        jjui/internal/ui/revisions/revisions.go:296 +0x391
jjui/internal/ui.Model.View({{0xc00023e030, {0xc00059a000, 0xce, 0x111}, 0x1, {0x0, 0x0}, 0x0, 0xc000124560, 0xffffffffffffffff, ...}, ...})
        jjui/internal/ui/ui.go:77 +0x40f
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00015c3c0, {0x622958?, 0xc0001ba008?}, 0xc000118150)
        github.com/charmbracelet/bubbletea@v1.2.4/tea.go:463 +0x84d
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00015c3c0)
        github.com/charmbracelet/bubbletea@v1.2.4/tea.go:595 +0xaad
main.main()
        jjui/cmd/jjui.go:14 +0x3a
```

</p>
</details> 

Similarly, the panic appears for [home-manager](https://github.com/nix-community/home-manager/) repository as well.
<details><summary>Panic log </summary>
<p>

```
Caught panic:

runtime error: slice bounds out of range [10:8]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc00013c3c0)
        github.com/charmbracelet/bubbletea@v1.2.4/tea.go:705 +0x8b
panic({0x596a00?, 0xc0003e6990?})
        runtime/panic.go:785 +0x132
jjui/internal/ui/revisions.SegmentedRenderer.Render({{{0x7563a0, 0x401, {0x0, 0x0}, 0x1, {0x622598, 0xc000132190}, {0x0, 0x0}, 0x0, ...}, ...}, ...}, ...)
        jjui/internal/ui/revisions/renderer.go:42 +0x2390
jjui/internal/jj.RenderRow({_, _}, {0x1, 0x1, 0x2, {{0xc00070b318, 0xa}, {0xc00070b323, 0x8}, {0xc00020dd80, ...}, ...}, ...}, ...)
        jjui/internal/jj/row.go:27 +0xad
jjui/internal/ui/revisions.Model.View({0xc0002bc090, {0xc000a10000, 0xd1b, 0xd55}, 0x1, {0x0, 0x0}, 0x0, 0xc0001424d0, 0xffffffffffffffff, ...})
        jjui/internal/ui/revisions/revisions.go:296 +0x391
jjui/internal/ui.Model.View({{0xc0002bc090, {0xc000a10000, 0xd1b, 0xd55}, 0x1, {0x0, 0x0}, 0x0, 0xc0001424d0, 0xffffffffffffffff, ...}, ...})
        jjui/internal/ui/ui.go:77 +0x40f
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00013c3c0, {0x622958?, 0xc0001a8008?}, 0xc0001b6070)
        github.com/charmbracelet/bubbletea@v1.2.4/tea.go:463 +0x84d
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00013c3c0)
        github.com/charmbracelet/bubbletea@v1.2.4/tea.go:595 +0xaad
main.main()
        jjui/cmd/jjui.go:14 +0x3a
```

</p>
</details> 

This issue was not present in the commit 525c8042a51710cdaefa91176af68a22ad0045bd.

**Comment by idursun** [comment]
Thanks for reporting this.

Yes, I was looking into it at the moment. It's failing to parse repositories with merge commits. I have to rework the parsing routines to account for this.

**Comment by idursun** [comment]
[`242f46e`](https://github.com/idursun/jjui/commit/242f46ed9de10540722934ae23f86b4455055eba) should fix the panicking in expense of rendering the graph slightly wrong.

Expected
```
@      l
├─┬─╮
│ │ ○  t
│ ○ │  p
│ ├─╯
○ │  q
├─╯
◆  z
```

Actual
```
@  l
○  t
│ ○  p
├─╯
│ ○  q
├─╯
◆  z
```

Not optimal, but better than panicking. I will keep this issue until I release a complete fix.

**Comment by Adda0** [comment]
Works "correctly" (as shown above) on the nixpkgs repo now. Thank you :+1: I will wait with updating the package until this is fixed.

**Comment by idursun** [comment]
Hey, this should have been fixed with the latest version. I have tested it against the nixpgs and home-manager repositories.

I have also added GHA workflows that run when `main` is updated and also another one that gets triggered when a release is cut along with a tag matching the release version. This should make it easy for you to know when to update the nix package! 

Thank you very much again.

**Comment by Adda0** [comment]
Thanks to this, I can now even let the nixpkgs CI to update the package automatically on release of a new version. Marvellous. I will update the nixpkgs package and test for myself. If anything comes up, I will let you know. Thanks for all the work on this tool.

**Comment by Adda0** [comment]
Tested 0.1. Everything works great. I therefore updated the package in nixpkgs to 0.1.

**Comment by idursun** [comment]
Awesome! Thanks!
